:toc:
:toc-placement!:
:toclevels: 4

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Changelog

== Unreleased
These changes are merged into the `main` branch, but have not been released. After merging pull requests (PRs) that are not immediately released into `main`, a tag is added appending the PR# to the current release. For example, if the release version/tag is `v0.0.0`, and PR# 15 is merged without a new release, the state of the codebase after that merge will be tagged as `v0.0.0.pr15`.

=== Breaking

=== Added

=== Bugfixes

=== Deleted
* Config validation constraint requiring `bastion-host` value to contain `bastion`. The host for tunneling for a project I am working on does not contain `bastion`

=== Deprecated/Will break in a future version

== 0.0.2 (2022-10-18)

=== Bugfixes
* Bumps version of `collectionspace-mapper` used, to get fixes for date processing (https://github.com/lyrasis/collectionspace_migration_tools/pull/17[PR#17])

=== Added
* `ohc` as valid profile in `config_client_contract` (https://github.com/lyrasis/collectionspace_migration_tools/pull/15[PR#15])

== 0.0.1 (2022-02-11)
* Added initial working version (skeletal!)

== 0.0.0 (2022-02-01)

* Added initial implementation.
