:toc:
:toc-placement!:
:toclevels: 4

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Changelog

== Unreleased
These changes are merged into the `main` branch, but have not been released. After merging pull requests (PRs) that are not immediately released into `main`, a tag is added appending the PR# to the current release. For example, if the release version/tag is `v0.0.0`, and PR# 15 is merged without a new release, the state of the codebase after that merge will be tagged as `v0.0.0.pr15`.

=== Breaking

* Client configuration management changes. To use new version:
** In your `system_config.yml` file:
*** Remove initial `system:` line and indetation of subsequent lines
*** Specify a `client_config_dir` location. See https://github.com/lyrasis/collectionspace_migration_tools/blob/main/doc/client_config_management.adoc[the client config management documentation page] for more information.
** Remove initial `redis:` line and indentation of subsequent lines from your `redis.yml` file if necessary
** After adding `client_config_dir` to your system config, you will need to run `thor config switch CONFIGNAME`
** Delete `client_config.yml` from the CMT repository base directory if it is still there.
** Changes were made to how the active config is stored/looked up after I discovered you could get stuck unable to switch away from an invalid config. The changes have other side benefits, too.

=== Added

* Optional `ingest_dir` setting in client config, which allows you to enter file name only when calling `thor batch add` `--csv` option for files in that default ingest directory.
* `thor cspace:reindex` command to trigger fulltext reindexing of the configured CollectionSpace instance

=== Bugfixes

* Report issue/don't fail messily when there is a missing item type value in a nonhierarchicalrelationship row
* Fix failure when reporting ingstat for batches with non-ingested items (i.e. items that failed map or upload steps and were thus not ingested)

=== Changed

=== Deleted

=== Deprecated/Will break in a future version

== 2.2.5 (2024-02-11)
=== Bugfixes
- Uses new version of `collectionspace-mapper` with a bugfix to prevent errors in reporting failures in date details mapping.

== 2.2.4 (2024-02-07)
=== Added
- Use new version of `collectionspace-mapper` that supports ingesting fields in same repeating field group as a structured date when you are ingesting structured date details for a date in that group.

== 2.2.3 (2024-02-01)
=== Bugfixes
- Use new version of `collectionspace-mapper` that supports retaining `%NULLVALUE%` fields as blank fields, and sets `shortid` correctly when mapping date details for authority records.

== 2.2.2 (2023-12-19)
=== Added
- `thor rt:delete_all` command for objects, procedures, and authorities. Do `thor rt help delete_all` for more details. (PR#42)
- Attempts to handle ingest errors using AWS Lambda logs -- still janky (PR#43, 44, 46)

=== Bugfixes
- Fix issue where application failed when there are duplicates reported in ingstat check (PR#45)
- Issue blocking ingest of chronology authority terms (PR#46)
- Update `collectionspace-mapper` to get fix for https://github.com/collectionspace/collectionspace-mapper/issues/148[#148] (PR#47)
- Fixes CLI output where processes didn't report about themselves correctly (PR#47)

== 2.2.1 (2023-04-26)
=== Bugfixes (related to media file ingest)
- Update `collectionspace-mapper` to get fix for https://github.com/lyrasis/collectionspace_migration_tools/issues/34[#34]
- Escape spaces in `mediafileuri` values, then url_encode them before construction S3 object key (https://github.com/lyrasis/collectionspace_migration_tools/issues/36[#36])

== 2.2.0 (2023-04-24)
=== Added
* Optional `aws_media_ingest_profile` system config setting, specifying AWS profile through which to access client media ingest bucket
* Optional `media_bucket` client config setting, specifying name of client media ingest bucket
* Two new commands to control the access policy of client media ingest bucket:
** thor bucket:public (makes bucket public, so media can be ingested)
** thor bucket:private (makes bucket private)

== 2.1.0 (2023-04-19)
=== Added
* Ability to ingest structured date details. See https://github.com/lyrasis/collectionspace_migration_tools/blob/main/doc/dates.adoc[Dates workflows documentation] for details.

== 2.0.0 (2023-03-10)
=== Breaking
* Upload of CS XML objects to S3 bucket for ingest now requires AWS profile to be set up on local system, and `aws_profile` setting in `system_config.yml`

=== Added
* New `media_with_blob_upload_delay` and `max_media_upload_threads` client config settings added (PR#27)

=== Bugfixes

=== Changed
* A number of client config settings now have defaults set by the tool, and do not need to be included in your config YML files unless you need to override the default values. See `CLIENT_CONFIG_DEFAULTS` in `lib/collectionspace_migration_tools/configuration.rb` for details. (PR#27)

== 1.1.0 (2022-12-14)

=== Added
* `thor csid:delete` command, allowing deletion of records by rectype+CSID. Do `thor csid help delete` for more details.

=== Changed
* Option for passing in custom source for `thor media:deriv_report` changed from `blob_data` to `csv` for better consistency with other commands, and less typing
* When uploading media with blob to S3, post-upload "sleep post #{identificationnumber}" message written to STDOUT. This is temporary behavior to give some feedback that progress is occurring with the expected upload delay, since the upload process now takes ages.
* Default system config `max_threads` increased to 10

=== Bugfixes
* Fixes issue in `thor media:deriv_report` where report generation would fail if there was only one derivative item for a blob.

== 1.0.0 (2022-12-08)
This is not a breaking change, but reflects this is now being used for CS migrations by more than one person.

=== Added

* When mapping a batch with `rectype=media`, rows with `blob_uri` values that cannot be converted into `URI` objects will get a "media_uri cannot be encoded as valid ingest URI. File ingest may not work as expected" warning. This is a warning, not an error, since CS can successfully ingest from file paths that do not convert to valid URIs.
* `thor decode:objects` that decodes object keys of all objects in S3 bucket, writing the results to a CSV in your base directory. This streamlines the process of getting the human-readable record id values for objects left in S3 bucket (assumed to be ingest errors)
* `thor media:blob_data` command to write report of all media procedures and, if present, their blob details. See https://github.com/lyrasis/collectionspace_migration_tools/blob/main/doc/media.adoc[media ingest documentation].
* `thor media:deriv_report` command to generate report of derivatives present for each `blobcsid` given. See https://github.com/lyrasis/collectionspace_migration_tools/blob/main/doc/media.adoc[media ingest documentation].
* Optional `:media_with_blob_upload_delay` client config setting. When uploading to S3 bucket for ingest, will wait this long after each media record that has an associated `mediaFileURI` value.

== 0.1.2 (2022-12-02)
* Use `collectionspace-mapper` v4.1.2 to get error handling bugfix

== 0.1.1 (2022-11-21)
=== Bugfixes
* Use `collectionspace-mapper` v4.1.1 to get scalar date creation bugfix

== 0.1.0 (2022-11-17)
=== Added
* Ability to ingest vocabulary terms. See https://github.com/lyrasis/collectionspace_migration_tools/blob/main/doc/add_vocabulary_terms.adoc[documentation] (https://github.com/lyrasis/collectionspace_migration_tools/pull/21[PR#21])

=== Changed
* `bin/console` now uses Pry instead of IRB (https://github.com/lyrasis/collectionspace_migration_tools/pull/20[PR#20])

=== Deleted
* Config validation constraint requiring `bastion-host` value to contain `bastion`. The host for tunneling for a project I am working on does not contain `bastion` (https://github.com/lyrasis/collectionspace_migration_tools/pull/19[PR#19])

== 0.0.2 (2022-10-18)

=== Bugfixes
* Bumps version of `collectionspace-mapper` used, to get fixes for date processing (https://github.com/lyrasis/collectionspace_migration_tools/pull/17[PR#17])

=== Added
* `ohc` as valid profile in `config_client_contract` (https://github.com/lyrasis/collectionspace_migration_tools/pull/15[PR#15])

== 0.0.1 (2022-02-11)
* Added initial working version (skeletal!)

== 0.0.0 (2022-02-01)

* Added initial implementation.
