:toc:
:toc-placement!:
:toclevels: 4

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Client config management

toc::[]

TIP: Do `thor config` to see all config-related commands. For details on a specific command, do `thor config help THECOMMAND`.

Client/project-specific configuration is stored in .yml files with the directory set as `client_config_dir` in your `system_config.yml`.

TIP: The config files must use the `.yml` file extension, not `.yaml` or anything else.

WARNING: Your `client_config_dir` must be in a secure location and must not be made public via version control or other methods.

== Creating a new client config

For each CS instance you need to work with, you need to create a client config .yml file inside your `client_config_dir`.

Copy `sample_client_config.yml` into `./config` with a name clearly identifying your instance (e.g. anthro_dev.yml, clientname_staging.yml, clientname_prod.yml) and edit it.

`sample_client_config.yml` is self-documenting.

If you want to start working with the new config, run `thor config:switch clientname_staging`.

== Active config

Do `thor config:show` to show the name of the active config

Do `thor config:show -v` to print the full config to screen.

== Updating a client config

Each time you run a command, the active config is read in from its .yml file.

As of v3.0.0, you no longer need to `thor config switch` after making changes.
