= Record type and functionality reference

== Tricky things/inconsistencies

* You can't derive an authority or vocabulary term's CSID or the path from its refname

== API path

[cols="1,3"]
|===
| record type | API path

| authorities
| /conceptauthorities/7022dcc2-2f66-4cb8-b768/items/0e4c2e31-88c0-45c1-950b

| blobs
| /blobs/9bd47a9b-1553-4ec7-8316

| collectionobjects
| /collectionobjects/09f531bd-4f12-4c36-9f92

| procedures
| /acquisitions/5043d8cc-9437-4bc7-92d1

| relations
| /relations/da044bc2-9fbf-474d-803a

| vocabularies
| vocabularies/e1401111-05c2-4d6c-bdc5/items/84c82c13-9d46-48a9-a8b9
|===

== refName

[cols="1,3"]
|===
| record type | refname

| authority terms
| urn:cspace:core.collectionspace.org:conceptauthorities:name(concept):item:name(Associatedconcept11581450962683)'Associated concept 1'

| blobs
| urn:cspace:core.collectionspace.org:blobs:id(9bd47a9b-1553-4ec7-8316)

| collectionobjects
| urn:cspace:core.collectionspace.org:collectionobjects:id(09f531bd-4f12-4c36-9f92)'Loaned object 1'

| procedures
| urn:cspace:core.collectionspace.org:acquisitions:id(5043d8cc-9437-4bc7-92d1)

| relations
| urn:cspace:core.collectionspace.org:relations:id(da044bc2-9fbf-474d-803a)

| vocabulary terms
| urn:cspace:core.collectionspace.org:vocabularies:name(annotationtype):item:name(additional_taxa)'additional taxa'
|===

== refName pattern

In this table:

* `services-url` refers to the value configured for that element in `application/tomcat-main/src/main/resources/defaults` files: `base-authority-#{authorityname}.xml`, `base-other-termlist.xml`, `base-collectionobject.xml`, `base-procedure-#{procedurename}.xml`, etc.
* `web-url` refers to values in `/record/instances/instance/web-url` in `application/tomcat-main/src/main/resources/defaults` files: `base-authority-#{authorityname}.xml` or `base-instance-vocabularies.xml`

[cols="1,3"]
|===
| record type | refname pattern

| authority vocab, vocabulary (top level, i.e. the vocabulary itself)
| urn:cspace:domain:services-url:name(web-url)'displayName'

| authority term
| urn:cspace:domain:services-url:name(web-url):item:name(term shortIdentifier)'termDisplayName'

| collectionobjects
| urn:cspace:domain:services-url:id(csid)'objectNumber'

| blobs, procedures, relations
| urn:cspace:domain:services-url:id(csid)

| vocabulary term - identifier is shortidentifier value of term
| urn:cspace:domain:vocabularies:name(web-url):item:name(term shortIdentifier)'displayName'

|===

== refcache population

=== terms (vocab, authority)
Purpose:

* lookup by HumanID (display name) to get:
** refname to use:
*** in fields in other records
*** in creating relations between terms (can be done by refname or csid)
** csid to use:
*** to look up whether a relationship exists or not
*** in creating relations between terms (can be done by refname or csid)

urn:cspace:core.collectionspace.org:conceptauthorities:name(concept):item:name(Associatedconcept11581450962683)'Associated concept 1'

Refname does not include CSID and can't be derived from it.

Relations between terms can only be looked up/found by subject term CSID and object term CSID

QUERY RESULT: refname, csid

RefCache get/put signature: type, subtype, displayName

=== collectionobjects

Purpose:

* lookup by HumanID (display name) to get:
** refname to use:
*** in fields in other records
*** in creating relations between terms (can be done by refname or csid)
** csid to use:
*** to look up whether a relationship exists or not
*** in creating relations between terms (can be done by refname or csid)

urn:cspace:core.collectionspace.org:collectionobjects:id(09f531bd-4f12-4c36-9f92)'Loaned object 1'

id = the csid and displayName is the HumanID, so this is the easiest one to deal with: all we need is the refname, **but we do still need to store the identifier


QUERY RESULT: refname

RefCache get/put signature: type, nil, displayName

=== procedures

urn:cspace:core.collectionspace.org:acquisitions:id(5043d8cc-9437-4bc7-92d1)

id = CSID, but the HumanID isn't in the refname

DB Query complication: the database table and the field name to get the HumanID from differs per procedure, but can probably be added to (or derived from?) CollectionSpace::Service fairly easily

QUERY RESULT: refname, HumanID

RefCache get/put signature: type, nil, HumanID

=== relations

urn:cspace:core.collectionspace.org:relations:id(da044bc2-9fbf-474d-803a)

The purpose of this one is a little different: We don't currently need to refer to relations as values in other fields, so we do not really need the refnames of relations.

For the migration support tool ONLY, we will need to cache whether or not a relation EXISTS, for record status checking







== service

Manually defined in https://github.com/collectionspace/collectionspace-client/blob/master/lib/collectionspace/client/service.rb

=== authorities

[source,ruby]
----
{:identifier=>"shortIdentifier",
 :ns_prefix=>"concepts",
 :path=>"conceptauthorities/urn:cspace:name(associated)/items",
 :term=>"conceptTermGroupList/0/termDisplayName"}
----

=== blobs

n/a

=== collectionobjects

[source,ruby]
----
{:identifier=>"objectNumber",
 :ns_prefix=>"collectionobjects",
 :path=>"collectionobjects",
 :term=>nil}
----

=== procedures

[source,ruby]
----
{:identifier=>"acquisitionReferenceNumber",
 :ns_prefix=>"acquisitions",
 :path=>"acquisitions",
 :term=>nil}
----

=== relations

[source,ruby]
----
{:identifier=>"csid", :ns_prefix=>"relations", :path=>"relations", :term=>nil}
----

=== vocabularies

[source,ruby]
----
{:identifier=>"shortIdentifier",
 :ns_prefix=>"vocabularyitems",
 :path=>"vocabularies/urn:cspace:name(annotationtype)/items",
 :term=>"displayName"}
----

== Database
=== Authority term variables

See `database_authority_variables.csv` file in the same directory as this document.

== Finding via `collectionspace-client`
=== authorities

[source,ruby]
----

----

=== blobs

[source,ruby]
----

----

=== collectionobjects

[source,ruby]
----

----

=== procedures

[source,ruby]
----

----

=== relations - CSID only

[source,ruby]
----
client.find_relation(subject_csid: 'f3a3c1a5-117b-45bc-974e', object_csid: '53080ab6-78e1-450a-984a')

URL to include type of relationship (i.e. predicate):
/relations?sbj=6f731eab-7cdc-4b12-ad5a&obj=da944ac7-9400-4467-9ff8&prd=affects
/relations?sbj=6f731eab-7cdc-4b12-ad5a&obj=da944ac7-9400-4467-9ff8&prd=hasBroader
----

=== vocabularies

[source,ruby]
----
# by displayName
client.find(type: 'vocabularies', subtype: 'annotationtype', value: 'additional taxa')
----

== API search responses

Only the `CollectionSpace::Response.parsed` value is shown below.

=== Successful, 1 record found
==== relations

[source,ruby]
----
{"relations_common_list"=>
    {"pageNum"=>"0",
     "pageSize"=>"25",
     "itemsInPage"=>"1",
     "totalItems"=>"1",
     "fieldsReturned"=>
      "subjectCsid|relationshipType|predicateDisplayName|relationshipMetaType|objectCsid|uri|csid|subject|object",
     "relation_list_item"=>
      {"uri"=>"/relations/da044bc2-9fbf-474d-803a",
       "csid"=>"da044bc2-9fbf-474d-803a",
       "subjectCsid"=>"f3a3c1a5-117b-45bc-974e",
       "relationshipType"=>"hasBroader",
       "predicate"=>"hasBroader",
       "objectCsid"=>"53080ab6-78e1-450a-984a",
       "subject"=>
        {"uri"=>"/collectionobjects/f3a3c1a5-117b-45bc-974e",
         "csid"=>"f3a3c1a5-117b-45bc-974e",
         "refName"=>
          "urn:cspace:core.collectionspace.org:collectionobjects:id(f3a3c1a5-117b-45bc-974e)'KMSTEST 1'",
         "name"=>nil,
         "number"=>"KMSTEST 1",
         "documentType"=>"CollectionObject"},
       "object"=>
        {"uri"=>"/collectionobjects/53080ab6-78e1-450a-984a",
         "csid"=>"53080ab6-78e1-450a-984a",
         "refName"=>
          "urn:cspace:core.collectionspace.org:collectionobjects:id(53080ab6-78e1-450a-984a)'BI TEST 1'",
         "name"=>nil,
         "number"=>"BI TEST 1",
         "documentType"=>"CollectionObject"}}}}
----

=== Successful, multiple records found
==== relations

[source,ruby]
----
{"relations_common_list"=>
  {"pageNum"=>"0",
   "pageSize"=>"25",
   "itemsInPage"=>"2",
   "totalItems"=>"2",
   "fieldsReturned"=>
    "subjectCsid|relationshipType|predicateDisplayName|relationshipMetaType|objectCsid|uri|csid|subject|object",
   "relation_list_item"=>
    [{"uri"=>"/relations/bbbfe1f8-8e42-40b1-be97",
      "csid"=>"bbbfe1f8-8e42-40b1-be97",
      "subjectCsid"=>"f3a3c1a5-117b-45bc-974e",
      "relationshipType"=>"hasBroader",
      "predicate"=>"hasBroader",
      "relationshipMetaType"=>"separable-part",
      "objectCsid"=>"53080ab6-78e1-450a-984a",
      "subject"=>
       {"uri"=>"/collectionobjects/f3a3c1a5-117b-45bc-974e",
        "csid"=>"f3a3c1a5-117b-45bc-974e",
        "refName"=>
         "urn:cspace:core.collectionspace.org:collectionobjects:id(f3a3c1a5-117b-45bc-974e)'KMSTEST 1'",
        "name"=>nil,
        "number"=>"KMSTEST 1",
        "documentType"=>"CollectionObject"},
      "object"=>
       {"uri"=>"/collectionobjects/53080ab6-78e1-450a-984a",
        "csid"=>"53080ab6-78e1-450a-984a",
        "refName"=>
         "urn:cspace:core.collectionspace.org:collectionobjects:id(53080ab6-78e1-450a-984a)'BI TEST 1'",
        "name"=>nil,
        "number"=>"BI TEST 1",
        "documentType"=>"CollectionObject"}},
     {"uri"=>"/relations/da044bc2-9fbf-474d-803a",
      "csid"=>"da044bc2-9fbf-474d-803a",
      "subjectCsid"=>"f3a3c1a5-117b-45bc-974e",
      "relationshipType"=>"hasBroader",
      "predicate"=>"hasBroader",
      "objectCsid"=>"53080ab6-78e1-450a-984a",
      "subject"=>
       {"uri"=>"/collectionobjects/f3a3c1a5-117b-45bc-974e",
        "csid"=>"f3a3c1a5-117b-45bc-974e",
        "refName"=>
         "urn:cspace:core.collectionspace.org:collectionobjects:id(f3a3c1a5-117b-45bc-974e)'KMSTEST 1'",
        "name"=>nil,
        "number"=>"KMSTEST 1",
        "documentType"=>"CollectionObject"},
      "object"=>
       {"uri"=>"/collectionobjects/53080ab6-78e1-450a-984a",
        "csid"=>"53080ab6-78e1-450a-984a",
        "refName"=>
         "urn:cspace:core.collectionspace.org:collectionobjects:id(53080ab6-78e1-450a-984a)'BI TEST 1'",
        "name"=>nil,
        "number"=>"BI TEST 1",
        "documentType"=>"CollectionObject"}}]}}
----

=== No records found
==== relations

[source,ruby]
----
{"relations_common_list"=>
  {"pageNum"=>"0", "pageSize"=>"25", "itemsInPage"=>"0", "totalItems"=>"0", "fieldsReturned"=>"subjectCsid|relationshipType|predicateDisplayName|relationshipMetaType|objectCsid|uri|csid|subject|object"}}
----
